### PR TITLE
multiagent related

### PR DESCRIPTION
**Pull request by eigebi**
接入maddpg算法
增加\agent\multiagent.py (初步)
接入particleenv，并修正了一个问题：done不应该在到达max_step的时候给True，否则Q估计不收敛
增加实验效果

### CODE REVIEW

**Comment by Yutongamber** [comment]
Hello Eigebi,
Thanks for lots of great work. A little updates needed:
1. Change the name "maddpg_customed" to "maddpg";
2. Move "model.py" from algo/ to networks/ (please refer to https://github.com/jidiai/ai_lib/blob/master/examples/algo/sac/sac.py#L12)

Thanks again. 
Best,
Yutong

**Review by Yutongamber — CHANGES_REQUESTED** [review]
Hello Eigebi,
Thanks for lots of great work. A little updates needed:

Change the name "maddpg_customed" to "maddpg";
Move "model.py" from algo/ to networks/ (please refer to https://github.com/jidiai/ai_lib/blob/master/examples/algo/sac/sac.py#L12)
Thanks again.
Best,
Yutong

**Comment by eigebi** [comment]
move model to networks; add encoder to ppo

**Comment by Yutongamber** [comment]
Hello Eigebi,
All good. Thanks~
Yutong

**Pull request merged**
